version: 2.1

executors:
  docker-executor:
    docker:
      - image: 'cimg/openjdk:17.0'
    working_directory: ~/repo

jobs:
  build-and-push-docker:
    docker:
      - image: circleci/python:3.8
    executor: docker-executor
    steps:
      - setup_remote_docker

      - checkout

      - run:
          name: Log in to Docker Hub
          command: |
            echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin

      - run:
          name: Build Docker Compose
          command: |
            docker-compose -f docker-compose.yml build

      - run:
          name: Run Tests
          command: |
            docker-compose -f docker-compose.yml up --abort-on-container-exit

      - run:
          name: Push Docker Images
          command: |
            docker-compose -f docker-compose.yml push

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push-docker
